// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCOujPnuJFU-0EeYqbW2AYV_iq2D4VpUo',
    appId: '1:903987622018:web:04915c750eb14c6080049b',
    messagingSenderId: '903987622018',
    projectId: 'iexam-49958',
    authDomain: 'iexam-49958.firebaseapp.com',
    storageBucket: 'iexam-49958.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjrMdHtxDUDMgLEL66redjo5hnaYjzLh0',
    appId: '1:903987622018:ios:fd950e60f443892680049b',
    messagingSenderId: '903987622018',
    projectId: 'iexam-49958',
    storageBucket: 'iexam-49958.firebasestorage.app',
    iosBundleId: 'com.example.iexam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCOujPnuJFU-0EeYqbW2AYV_iq2D4VpUo',
    appId: '1:903987622018:web:f5068d6e95eda9fe80049b',
    messagingSenderId: '903987622018',
    projectId: 'iexam-49958',
    authDomain: 'iexam-49958.firebaseapp.com',
    storageBucket: 'iexam-49958.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjrMdHtxDUDMgLEL66redjo5hnaYjzLh0',
    appId: '1:903987622018:ios:fd950e60f443892680049b',
    messagingSenderId: '903987622018',
    projectId: 'iexam-49958',
    storageBucket: 'iexam-49958.firebasestorage.app',
    iosBundleId: 'com.example.iexam',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCozkFSzh6f-W24CfYNwRd1f3t3Nz6-h5g',
    appId: '1:903987622018:android:603f525eaefddc5580049b',
    messagingSenderId: '903987622018',
    projectId: 'iexam-49958',
    storageBucket: 'iexam-49958.firebasestorage.app',
  );

}